/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>api token</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.api_token#getNom_token <em>Nom token</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.api_token#getToken <em>Token</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getapi_token()
 * @model
 * @generated
 */
public interface api_token extends EObject
{
  /**
   * Returns the value of the '<em><b>Nom token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom token</em>' attribute.
   * @see #setNom_token(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getapi_token_Nom_token()
   * @model
   * @generated
   */
  String getNom_token();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.api_token#getNom_token <em>Nom token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom token</em>' attribute.
   * @see #getNom_token()
   * @generated
   */
  void setNom_token(String value);

  /**
   * Returns the value of the '<em><b>Token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Token</em>' attribute.
   * @see #setToken(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getapi_token_Token()
   * @model
   * @generated
   */
  String getToken();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.api_token#getToken <em>Token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Token</em>' attribute.
   * @see #getToken()
   * @generated
   */
  void setToken(String value);

} // api_token
