/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.array#getTargets <em>Targets</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.array#getArray_names <em>Array names</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.array#getArray <em>Array</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getarray()
 * @model
 * @generated
 */
public interface array extends EObject
{
  /**
   * Returns the value of the '<em><b>Targets</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Targets</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getarray_Targets()
   * @model unique="false"
   * @generated
   */
  EList<String> getTargets();

  /**
   * Returns the value of the '<em><b>Array names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array names</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getarray_Array_names()
   * @model unique="false"
   * @generated
   */
  EList<String> getArray_names();

  /**
   * Returns the value of the '<em><b>Array</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.arrayElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getarray_Array()
   * @model containment="true"
   * @generated
   */
  EList<arrayElement> getArray();

} // array
