/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>identify</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.identify#getIdentify_array <em>Identify array</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getidentify()
 * @model
 * @generated
 */
public interface identify extends EObject
{
  /**
   * Returns the value of the '<em><b>Identify array</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.array_content}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identify array</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getidentify_Identify_array()
   * @model containment="true"
   * @generated
   */
  EList<array_content> getIdentify_array();

} // identify
