/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.loop#getLoop_array <em>Loop array</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getloop()
 * @model
 * @generated
 */
public interface loop extends EObject
{
  /**
   * Returns the value of the '<em><b>Loop array</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.array}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop array</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getloop_Loop_array()
   * @model containment="true"
   * @generated
   */
  EList<array> getLoop_array();

} // loop
