/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Tokens</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TOKENS = 0;

  /**
   * The feature id for the '<em><b>Arrays</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ARRAYS = 1;

  /**
   * The feature id for the '<em><b>Loops</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__LOOPS = 2;

  /**
   * The feature id for the '<em><b>Identifications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__IDENTIFICATIONS = 3;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.identifyImpl <em>identify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.identifyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getidentify()
   * @generated
   */
  int IDENTIFY = 1;

  /**
   * The feature id for the '<em><b>Identify array</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFY__IDENTIFY_ARRAY = 0;

  /**
   * The number of structural features of the '<em>identify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.arrayImpl <em>array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.arrayImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getarray()
   * @generated
   */
  int ARRAY = 2;

  /**
   * The feature id for the '<em><b>Targets</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__TARGETS = 0;

  /**
   * The feature id for the '<em><b>Array names</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__ARRAY_NAMES = 1;

  /**
   * The feature id for the '<em><b>Array contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY__ARRAY_CONTENTS = 2;

  /**
   * The number of structural features of the '<em>array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.array_contentImpl <em>array content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.array_contentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getarray_content()
   * @generated
   */
  int ARRAY_CONTENT = 3;

  /**
   * The feature id for the '<em><b>Array</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_CONTENT__ARRAY = 0;

  /**
   * The number of structural features of the '<em>array content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_CONTENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.arrayElementImpl <em>array Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.arrayElementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getarrayElement()
   * @generated
   */
  int ARRAY_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Identify array</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ELEMENT__IDENTIFY_ARRAY = IDENTIFY__IDENTIFY_ARRAY;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ELEMENT__VALUE = IDENTIFY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>array Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ELEMENT_FEATURE_COUNT = IDENTIFY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.api_tokenImpl <em>api token</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.api_tokenImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getapi_token()
   * @generated
   */
  int API_TOKEN = 5;

  /**
   * The feature id for the '<em><b>Nom token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API_TOKEN__NOM_TOKEN = 0;

  /**
   * The feature id for the '<em><b>Token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API_TOKEN__TOKEN = 1;

  /**
   * The number of structural features of the '<em>api token</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API_TOKEN_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getTokens <em>Tokens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tokens</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getTokens()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tokens();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getArrays <em>Arrays</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arrays</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getArrays()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Arrays();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Model#getLoops <em>Loops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Loops</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getLoops()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Loops();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getIdentifications <em>Identifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Identifications</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getIdentifications()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Identifications();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.identify <em>identify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>identify</em>'.
   * @see org.xtext.example.mydsl.myDsl.identify
   * @generated
   */
  EClass getidentify();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.identify#getIdentify_array <em>Identify array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Identify array</em>'.
   * @see org.xtext.example.mydsl.myDsl.identify#getIdentify_array()
   * @see #getidentify()
   * @generated
   */
  EReference getidentify_Identify_array();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.array <em>array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>array</em>'.
   * @see org.xtext.example.mydsl.myDsl.array
   * @generated
   */
  EClass getarray();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.array#getTargets <em>Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Targets</em>'.
   * @see org.xtext.example.mydsl.myDsl.array#getTargets()
   * @see #getarray()
   * @generated
   */
  EAttribute getarray_Targets();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.array#getArray_names <em>Array names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Array names</em>'.
   * @see org.xtext.example.mydsl.myDsl.array#getArray_names()
   * @see #getarray()
   * @generated
   */
  EAttribute getarray_Array_names();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.array#getArray_contents <em>Array contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Array contents</em>'.
   * @see org.xtext.example.mydsl.myDsl.array#getArray_contents()
   * @see #getarray()
   * @generated
   */
  EReference getarray_Array_contents();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.array_content <em>array content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>array content</em>'.
   * @see org.xtext.example.mydsl.myDsl.array_content
   * @generated
   */
  EClass getarray_content();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.array_content#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Array</em>'.
   * @see org.xtext.example.mydsl.myDsl.array_content#getArray()
   * @see #getarray_content()
   * @generated
   */
  EReference getarray_content_Array();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.arrayElement <em>array Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>array Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.arrayElement
   * @generated
   */
  EClass getarrayElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.arrayElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.arrayElement#getValue()
   * @see #getarrayElement()
   * @generated
   */
  EAttribute getarrayElement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.api_token <em>api token</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>api token</em>'.
   * @see org.xtext.example.mydsl.myDsl.api_token
   * @generated
   */
  EClass getapi_token();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.api_token#getNom_token <em>Nom token</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom token</em>'.
   * @see org.xtext.example.mydsl.myDsl.api_token#getNom_token()
   * @see #getapi_token()
   * @generated
   */
  EAttribute getapi_token_Nom_token();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.api_token#getToken <em>Token</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Token</em>'.
   * @see org.xtext.example.mydsl.myDsl.api_token#getToken()
   * @see #getapi_token()
   * @generated
   */
  EAttribute getapi_token_Token();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Tokens</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TOKENS = eINSTANCE.getModel_Tokens();

    /**
     * The meta object literal for the '<em><b>Arrays</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ARRAYS = eINSTANCE.getModel_Arrays();

    /**
     * The meta object literal for the '<em><b>Loops</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__LOOPS = eINSTANCE.getModel_Loops();

    /**
     * The meta object literal for the '<em><b>Identifications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__IDENTIFICATIONS = eINSTANCE.getModel_Identifications();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.identifyImpl <em>identify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.identifyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getidentify()
     * @generated
     */
    EClass IDENTIFY = eINSTANCE.getidentify();

    /**
     * The meta object literal for the '<em><b>Identify array</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IDENTIFY__IDENTIFY_ARRAY = eINSTANCE.getidentify_Identify_array();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.arrayImpl <em>array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.arrayImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getarray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getarray();

    /**
     * The meta object literal for the '<em><b>Targets</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY__TARGETS = eINSTANCE.getarray_Targets();

    /**
     * The meta object literal for the '<em><b>Array names</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY__ARRAY_NAMES = eINSTANCE.getarray_Array_names();

    /**
     * The meta object literal for the '<em><b>Array contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY__ARRAY_CONTENTS = eINSTANCE.getarray_Array_contents();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.array_contentImpl <em>array content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.array_contentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getarray_content()
     * @generated
     */
    EClass ARRAY_CONTENT = eINSTANCE.getarray_content();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_CONTENT__ARRAY = eINSTANCE.getarray_content_Array();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.arrayElementImpl <em>array Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.arrayElementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getarrayElement()
     * @generated
     */
    EClass ARRAY_ELEMENT = eINSTANCE.getarrayElement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_ELEMENT__VALUE = eINSTANCE.getarrayElement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.api_tokenImpl <em>api token</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.api_tokenImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getapi_token()
     * @generated
     */
    EClass API_TOKEN = eINSTANCE.getapi_token();

    /**
     * The meta object literal for the '<em><b>Nom token</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute API_TOKEN__NOM_TOKEN = eINSTANCE.getapi_token_Nom_token();

    /**
     * The meta object literal for the '<em><b>Token</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute API_TOKEN__TOKEN = eINSTANCE.getapi_token_Token();

  }

} //MyDslPackage
