/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.api_token;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>api token</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.api_tokenImpl#getNom_token <em>Nom token</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.api_tokenImpl#getToken <em>Token</em>}</li>
 * </ul>
 *
 * @generated
 */
public class api_tokenImpl extends MinimalEObjectImpl.Container implements api_token
{
  /**
   * The default value of the '{@link #getNom_token() <em>Nom token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom_token()
   * @generated
   * @ordered
   */
  protected static final String NOM_TOKEN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNom_token() <em>Nom token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom_token()
   * @generated
   * @ordered
   */
  protected String nom_token = NOM_TOKEN_EDEFAULT;

  /**
   * The default value of the '{@link #getToken() <em>Token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToken()
   * @generated
   * @ordered
   */
  protected static final String TOKEN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getToken() <em>Token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToken()
   * @generated
   * @ordered
   */
  protected String token = TOKEN_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected api_tokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.API_TOKEN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNom_token()
  {
    return nom_token;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNom_token(String newNom_token)
  {
    String oldNom_token = nom_token;
    nom_token = newNom_token;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.API_TOKEN__NOM_TOKEN, oldNom_token, nom_token));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getToken()
  {
    return token;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setToken(String newToken)
  {
    String oldToken = token;
    token = newToken;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.API_TOKEN__TOKEN, oldToken, token));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.API_TOKEN__NOM_TOKEN:
        return getNom_token();
      case MyDslPackage.API_TOKEN__TOKEN:
        return getToken();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.API_TOKEN__NOM_TOKEN:
        setNom_token((String)newValue);
        return;
      case MyDslPackage.API_TOKEN__TOKEN:
        setToken((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.API_TOKEN__NOM_TOKEN:
        setNom_token(NOM_TOKEN_EDEFAULT);
        return;
      case MyDslPackage.API_TOKEN__TOKEN:
        setToken(TOKEN_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.API_TOKEN__NOM_TOKEN:
        return NOM_TOKEN_EDEFAULT == null ? nom_token != null : !NOM_TOKEN_EDEFAULT.equals(nom_token);
      case MyDslPackage.API_TOKEN__TOKEN:
        return TOKEN_EDEFAULT == null ? token != null : !TOKEN_EDEFAULT.equals(token);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nom_token: ");
    result.append(nom_token);
    result.append(", token: ");
    result.append(token);
    result.append(')');
    return result.toString();
  }

} //api_tokenImpl
